### ISSUE TITLE
neon yellow JoyCons: no gyro input registered (if it should)

### ISSUE THREAD

**Issue by uani3** [mfosse/JoyCon-Driver#21]
--enable-gyro (in conjunction with --auto-center, I haven't tried without, sorry for not thinking about it before) has the Ri values not changing in either vJoy monitor or Windows game controller configuration (Windows 10). I suppose from your screenshots of vJoy Ri are the gyro readings.

If this should work at all already I'm mentioning this :) I have the neon yellow JoyCons.

If I can run some raw readings logger for you or similar I'm glad to assist!

**Comment by mfosse** [comment]
--enable-gyro only shows readings from the left joycon, it's still a work in progress and there's not enough sliders in vJoy to show all the info there, I'll figure it out soon after I get back from CA (July 4th)

**Comment by mfosse** [comment]
The joycons being yellow shouldn't make a difference at all btw

**Comment by VapidLinus** [comment]
@mfosse Hello, did you manage to get gyro working for the right JoyCon? I downloaded the latest release build but it doesn't seem to work on the right JoyCon at the moment.

I'd happily donate some money if you get it working. Planning it using the JoyCon gyro as a mouse, similar to how the controllers for most smart TVs do it :)

**Comment by VapidLinus** [comment]
Actually, I'm not getting it to work with the left JoyCon either. Running "start joycon-driver.exe --auto-center" makes "vJoy Device #1" report inputs successfully.  Running "start joycon-driver.exe --enable-gyro" leaves none of the vJoy devices reporting any input.

Also tried  "start joycon-driver.exe --auto-center --enable-gyro" with no same results.

**Comment by mfosse** [comment]
If you'd like to donate, (very appreciated) I have a PayPal at matt.cfosse@gmail.com; Although right now I'm on vacation in NYC, but the issue isn't getting the info anymore, it's how to use it for games since it doesn't translate to joysticks 1:1, I'm pretty sure I'm gonna make it control the mouse with some sensitivity controls, I'll have more time when I fly to Minnesota (I leave Thursday) but when I build from my laptop it'll only be windows 10 (as opposed to windows 8.1+)

you might want to try adding --combine
You'll need to configure vJoy device #2 to include RZ, SL0, and SL1 if you want any accelerometer/gyro data to show up, right now it just shows accelerometer data btw (there aren't enough sliders in vJoy to show both gyro and accelerometer data, much less from both at once) it shows data from left joycon if there is only one joycon connected, and from the right joycon if 2 are connected

Sorry this ended up being really long.
