### ISSUE TITLE
when the joycons connected together, my PC takes inout from the vjoy device and also from the joycon itself

### ISSUE THREAD

**Issue by asafjac** [mfosse/JoyCon-Driver#29]
![default](https://user-images.githubusercontent.com/31475836/29871697-6d66b588-8d95-11e7-89c0-fc99e964f921.png)
![default](https://user-images.githubusercontent.com/31475836/29871756-a63c8bc6-8d95-11e7-9dbd-fc0ad3b65763.png)
![default](https://user-images.githubusercontent.com/31475836/29871829-eac029ce-8d95-11e7-8dcb-0780fd2b4cb0.png)

**Comment by mfosse** [comment]
This is expected behavior, I'm not sure there's much I can do about it...

**Comment by mfosse** [comment]
To be more specific, the vJoy device doesn't prevent windows from see the joycon as a regular input device, so it's expected to still show up as a wireless gamepad

**Comment by asafjac** [comment]
So I can't use it for gaming?

**Comment by mfosse** [comment]
@asafjac are you using x360ce? xOutput? what game?

**Comment by moracabanas** [comment]
I have the same issue, I used XOutput woth Cuphead and Duck Game, and controls are mixing Xinpunt data with separate joycon Dinput. Exclusive mode is not working. Im in a W10 Developer preview but I cannot try it in last stable W10 right now.

**Comment by moracabanas** [comment]
You can see for example if you turn right on the left joycon it is actually going down on the separate dinput separate joyvon, so you  can actually see Xbox360 game buttons swap with just normal buttons on game explanations

**Comment by mfosse** [comment]
looking into this further, it looks like this problem is a bit beyond the scope of what I'm capable of in any reasonable amount of time, fortunately, it looks like this project was built for this exact problem: https://github.com/nefarius/ViGEm/tree/master/Sys/HidGuardian

It looks like it's still a work in progress though but you can test it here:
https://vigem.org/hidguardian-v2-secret-alpha-test-area/
