### ISSUE TITLE
Cannot compile 64 bit version

### ISSUE THREAD

**Issue by alicealysia** [mfosse/JoyCon-Driver#50]
When attempting to compile in 64 bit VS tells me that the module device is 32 bit.
32 bit version compiles fine, but it doesn't seem to run on my pc. Which is weird, because the last release does.

This is annoying because I made some tweaks that will make it way better (including deadzones for thumbsticks and gyro. I also want to add gyro calibration, as well as native motion control support for apps like Cemu)

**Comment by mfosse** [comment]
I don't know why it doesn't run on your pc when compiled as 32 bit (how exactly does it not run?)

It won't work when compiled as 64 bit because all of the dependencies are compiled as 32 bit, I did this so it would be compatible with 32 bit systems

If you add any of these things that'd be a lot of help since I've been busier than I originally thought

**Comment by alicealysia** [comment]
So when I say it doesn't run, I mean neither the gui or command prompt open up. Note that this is when i compile it, so it might have been something I changed or added.
I'll try running it as an admin or in compatibility mode tonight, and I'll also pick through all the code I changed.

**Comment by alicealysia** [comment]
so as it turn out, I didn't add the new settings for gyro deadzone or joystick deadzone correctly, as they are causing an invalid stof argument to occur

**Comment by mfosse** [comment]
@alicealysia Can you make a pull request so I can merge it?
