### ISSUE TITLE
Doesn't work at random times

### ISSUE THREAD

**Issue by xBitsoft** [mfosse/JoyCon-Driver#79]
Most of the times the program runs fine but occasionally I get this: https://imgur.com/a/mbitKts

Restarting the program does nothing, nor does running as admin. The only thing that sometimes works is disconnecting and reconnecting the joycons otherwise I have to reboot my computer. But it takes time to do these every time the problem occurs. Unfortunately I don't have much other information. Writing to debug file simply creates a 0 KB empty file.

Also, off-topic: can we get an option to minimize to the system tray please?

**Comment by mfosse** [comment]
It's not random, this happens when you close the program (through the close or quit button), it disconnects and turns of the joycons, this is so that they don't stay connected and drain the battery, all you need to do is press any of the buttons on the joycons to wake them up (they will automatically reconnect after a few seconds)

As for the system tray thing, it's already been requested, and I'll probably do it eventually, but I'm not making any major UI changes right now since I plan on switching to At, which will be it's own complete UI change, but not before finals are over

**Comment by xBitsoft** [comment]
I found the problem. It was to do with the way I set up things on my PC. If anyone else has the same complex setup like me, the problem may be that when you close HIDer you aren't closing it properly. Forcing HIDer to close prevents it from running some crucial code that it executes when it closes normally. Even though the process doesn't show up under Task Manager Details, it still needs to run that code to clean things up after itself.

Feel free to close this issue.
