### ISSUE TITLE
Fixed widget positioning doesn't work correctly on HiDPI monitors

### ISSUE THREAD

**Issue by lewtds** [mfosse/JoyCon-Driver#90]
Pretty self-explanatory...

![capture](https://user-images.githubusercontent.com/1055960/39964797-3b54e2a8-5695-11e8-9fc3-25194ea25e80.PNG)

**Comment by mfosse** [comment]
Lol, this has to do with WxWidgets, but on my laptop (with a 3000x2000px resolution) it's just really small, but I'm able to fix it by right clicking the exe, going to properties -> compatibility -> Override high DPI scaling behavior and trying the different options

I'm gonna close this since it's not something I can easily fix and I plan to switch the program over to Qt anyways
